### ISSUE TITLE
Support for GxGDEM0213B74/GxGDEM0213B74.h

### ISSUE THREAD

**Issue by geeuk** [gagauz/weatherdisplay#6]
Hi 

I am total newbie but I trying to use GxGDEM0213B74/GxGDEM0213B74.h with your code.

How can I do this in VS  ?

Thanks,
Gokhan

**Comment by gagauz** [comment]
Try to change in `display.h` import line:
`#include <GxGDEH0213B73/GxGDEH0213B73.h>`
to your display driver.

**Comment by geeuk** [comment]
Thank you for your fast reply. I done it. It's working. 

I downloaded src from [](https://github.com/lewisxhe/GxEPD/archive/refs/heads/master.zip) moved to src (.pio\libdeps\esp32dev\GxEPD\src) folder of project and renamed originalsrc of original folder.

I added these to display.h

#define LILYGO_T5_V213
#include <GxGDEM0213B74/GxGDEM0213B74.h>

It complained about GFX fonts so I used the original GxFont_GFX.cpp and GxFont_GFX.h

May be if I just used GxGDEM0213B74 it would of worked but yes newbie always takes longer ways :) 

Quick question Is it normal for the time not update every minute ? Time is not ment to be live?

**Comment by gagauz** [comment]
> Quick question Is it normal for the time not update every minute ? Time is not ment to be live?
That's right. The controller wakes up, requests changes and sleep every 30 min. It allows to work from the battery much longer.

**Comment by geeuk** [comment]
Thank you for your help and building this project. Everything is working fine.
